---
# Sets up servers to be used to push ansible configs out

- hosts: ansible-staging
  user: root
  tasks:

    - include: includes/install-from-ppa
      vars:
        package: ansible
        ppa: ppa:rquillo/ansible
        ppa_mint: deb http://ppa.launchpad.net/rquillo/ansible/ubuntu raring main

    - name: install git
      apt: pkg=git
